import os
import itertools
import numpy as np
import pandas as pd
import cooler
from hicrep.utils import readMcool
from hicrep import hicrepSCC
from .hicgeneral import get_cool_name

# General function for calculating scc's
def calc_scc_file(fcool1: str, fcool2: str, bin_size: int = None, h=1, 
                  d_bp_max: int = 1_000_000, b_down_sample: bool = False, 
                   chr_names: list = None, chr_exclude: set = None):
    '''
        Takes two .cool/.mcool files and returns an array of SCC scores for all chromosomes shared
        between the input files.

        Parameters
        ----------
        fcool1 : str     
            Path to a .cool/.mcool file.
        fcool2 : str     
            Path to a .cool/.mcool file.
        bin_size : int   
            Bin size in both mcool files that will be used to compute the SCC.
            If inputs are .cool files, this parameter is ignored.
            Default = None.
        h : int          
            The smoothing parameter used for the 2D mean filter smoothing.
            Default = 1.
        d_bp_max : int   
            The maximum genomic distance between contacts that will be considered for
            calculating the SCC.
            Default = 1_000_000
        b_down_samp : bool 
            Determines if the input file with more contacts should be downsized
            to the same number of contacts as the other input file.
            Default = False.
        chr_names : list[str]
            Chromosomes whose SCC should be calculated.
            Default = None, takes all chromosomes.
        chr_exclude : set[str]
            Chromosomes that should be ignored for SCC calculation (set).
            Default = None, excludes no chromosomes.

        Returns
        -------
        scc : list[float]
            List of SCCs, in the order of chromosomes from the .cool/.mcool files.
    '''
    # Extract file extension
    ext1 = os.path.splitext(fcool1)[1]
    ext2 = os.path.splitext(fcool2)[1]
    
    # File errors
    if not os.path.exists(fcool1):
        raise FileNotFoundError(f"The specified file does not exist: '{fcool1}'")
    if not os.path.exists(fcool2):
        raise FileNotFoundError(f"The specified file does not exist: '{fcool2}'")

    # Extension errors
    allowed_files = (".cool", ".mcool")
    if any(ext not in allowed_files for ext in (ext1, ext2)):
        raise ValueError(f"One or both files are not .cool or .mcool: {ext1} and {ext2}")

    # Handling .cool vs .mcool
    if ext1 == ".cool":
        cool1, bin_size_1 = readMcool(fcool1, -1)
    else:
        # Raise error if no bin size is specified
        if bin_size == None:
            raise ValueError("No bin size specified for .mcool file")
        
        cool1, bin_size_1 = readMcool(fcool1, bin_size)

    if ext2 == ".cool":
        cool2, bin_size_2 = readMcool(fcool2, -1)
    else:
        # Raise error if no bin size is specified
        if bin_size == None:
            raise ValueError("No bin size specified for .mcool file")
        
        cool2, bin_size_2 = readMcool(fcool2, bin_size)

    # Handling different bin sizes
    if bin_size_1 != bin_size_2:
        raise ValueError(f"Bin sizes between input files differ: {bin_size_1} and {bin_size_2}")
    bin_size = bin_size_1

    # Calculating SCCs
    scc = hicrepSCC(cool1, cool2, h, d_bp_max, b_down_sample, chr_names, chr_exclude)

    return scc

def avg_scc(scc):
    '''
        Takes an array of SCCs generated by calc_scc and returns the mean SCC value.

        Parameters
        ----------
        scc : np.ndarray     
            Array of SCCs produced by calc_scc.

        Returns
        -------
        avg : np.float64
            The mean of the provided array of SCCs
    '''
    avg = np.average(scc)
    return avg

def avg_scc_weighted(scc, chr_lengths):
    '''
        Takes an array of SCCs generated by calc_scc and returns the weighted mean
        SCC value based on the length of the chromosomes used to calculate the SCCs.

        Parameters
        ----------
        scc : np.ndarray
            Array of SCCs produced by calc_scc.
        chr_lengths : list[int]  
            List of chromosome lengths, corresponding in order to the order
            for these chromosomes used to calculate the SCCs.
        
        Returns
        -------
        avg : np.float64
            The weighted mean of the provided array of SCCs.
    '''
    # TODO: errors for data types
    # TODO: check if it is possible to extract chr_lengths from .cool/.mcool directly

    weights = []
    total_length = np.sum(chr_lengths)

    for chr in chr_lengths:
        weights.append(chr/total_length)

    avg = np.average(scc, weights=weights)

    return avg

def bulk_compare(files, bin_size, h=1, d_bp_max=1_000_000, b_down_sample=False, 
                   chr_names = None, chr_exclude = None, chr_lengths = None):
    '''
        Takes a list of .mcool or .cool files and returns (1) a dictionary of SCC arrays
        for each chromosome and (2) a dictionary of the averages of these SCCs. The
        average is weighted by chromosome length if a list of chromosome lengths (in
        the appropriate order) is provided.

        Parameters
        ----------
        files : list[str]      
            A list of all .mcool/.cool files.
        bin_size : int    
            Bin size in both mcool files that will be used to compute the SCC.
            If inputs are .cool files, this parameter is ignored.
        h : int          
            The smoothing parameter used for the 2D mean filter smoothing.
            Default = 1.
        d_bp_max : int   
            The maximum genomic distance between contacts that will be considered for
            calculating the SCC.
            Default = 1_000_000
        b_down_samp : bool 
            Determines if the input file with more contacts should be downsized
            to the same number of contacts as the other input file.
            Default = False.
        chr_names : list[str]   
            Chromosomes whose SCC should be calculated.
            Default = None, takes all chromosomes.
        chr_exclude : set[str]
            Chromosomes that should be ignored for SCC calculation.
            Default = None, excludes no chromosomes.
        chr_lengths : list[str]  
            The lengths of the chromosomes for the included data.
            Default = None, uses a non-weighted average instead.

        Returns
        -------
        scc_map : dict
            All SCC arrays for all comparisons.
        acc_avg_map : dict
            All (weighted) averages for the SCC arrays.
    '''
    # Mapping file path to file names
    file_name_map = {file: os.path.splitext(os.path.basename(file))[0] for file in files}

    # Declare dict for comparisons
    scc_map = {}
    scc_avg_map = {}
    # Iterate over unique pairs
    for file1, file2 in itertools.combinations(files, 2):
        combination = f"{file_name_map[file1]}x{file_name_map[file2]}"
        scc_map[combination] = calc_scc_file(file1, file2, bin_size, h, d_bp_max, b_down_sample, chr_names,
                                        chr_exclude)
        
        # Calculate averages
        if chr_lengths == None:
            scc_avg_map[combination] = avg_scc(scc_map[combination])
        else:
            scc_avg_map[combination] = avg_scc_weighted(scc_map[combination], chr_lengths)

    return scc_map, scc_avg_map

def bulk_compare_ref(clrs: list[cooler.api.Cooler], ref: cooler.api.Cooler, h: int, d_bp_max: int,
                     b_down_sample: bool = False, chr_names: list[str] = None, 
                     chr_exclude: set[str] = None):
    '''
        Takes a list of coolers and a reference cooler and computes the scc
        between each cooler in the list and the reference cooler based on the
        arguments provided.

        Parameters
        ----------
        clrs : list[cooler.api.Cooler] 
            List of cooler objects to be compared to the reference.
        ref : cooler.api.Cooler
            The reference cooler to which the list will be compared
        h : int              
            The smoothing parameter used for the 2D mean filter smoothing.
        d_bp_max : int      
            The maximum genomic distance between contacts that will be considered for
            calculating the SCC.
        b_down_sample : bool 
            Determines if the input file with more contacts should be downsized
            to the same number of contacts as the other input file.
            Default = False.
        chr_names : list[str]
            Chromosomes whose SCC should be calculated.
            Default = None, takes all chromosomes.
        chr_exclude : set[str]
            Chromosomes that should be ignored for SCC calculation.
            Default = None, excludes no chromosomes.
        
        Returns
        -------
        scc_scores : dict
            A dictonary with names of each cooler object as the keys and the computed scc's
            as the values.
    '''
    scc_scores = {}
    
    # Loop through all coolers, get their names and compute sccs, add to dictonary
    for clr in clrs:
        filename = get_cool_name(clr)
        scc = hicrepSCC(clr, ref, h, d_bp_max, b_down_sample, chr_names, chr_exclude)
        
        # Only grab the float if scc only has 1 element
        if len(scc) == 1:
            scc_scores[filename] = scc[0]
        else:
            scc_scores[filename] = scc

    return scc_scores

def scc_compare_lists(clrs1: list[cooler.api.Cooler], clrs2: list[cooler.api.Cooler], h: int, d_bp_max: int, 
                      b_down_sample: bool = False, chr_names: list[str] = None, chr_exclude: set[str] = None):
    '''
        Takes two lists of coolers and returns a dataframe with all SCC comparisons
        between the coolers in said lists. If more than 1 chromosome is considered,
        returns the average SCC.

        Parameters
        ----------
        clrs1 : list[cooler.api.Cooler]          
            List of cooler objects to be compared.
        clrs2 : list[cooler.api.Cooler]          
            List of cooler objects to be compared.
        h : int              
            The smoothing parameter used for the 2D mean filter smoothing.
        d_bp_max : int      
            The maximum genomic distance between contacts that will be considered for
            calculating the SCC.
        b_down_sample : bool  
            Determines if the input file with more contacts should be downsized
            to the same number of contacts as the other input files.
            Default = False.
        chr_names : list[str]       
            Chromosomes whose SCC should be calculated.
            Default = None, takes all chromosomes.
        chr_exclude : set[str]    
            Chromosomes that should be ignored for SCC calculation.
            Default = None, excludes no chromosomes.

        Returns:
        df : pd.DataFrame
            A pandas dataframe with all comparisons.
    '''

    # Initialize empty dict
    dict = {}

    # Loop through all files and calculate sccs
    for clr in clrs2:
        file_name = get_cool_name(clr)
        comparisons = bulk_compare_ref(clrs1, clr, h, d_bp_max, b_down_sample, chr_names, chr_exclude)
        dict[file_name] = comparisons
    
    # Convert to dataframe
    df = pd.DataFrame(dict)

    return df

def scc_compare_matrix(clrs: list[cooler.api.Cooler], h: int, d_bp_max: int, b_down_sample: bool = False, 
                       chr_names: list[str] = None, chr_exclude: set[str] = None):
    '''
        Takes a list of coolers and returns a dataframe with all SCC comparisons
        between the coolers in said list. If more than 1 chromosome is considered,
        returns the average SCC.

        Parameters
        ----------
        clrs : list[cooler.api.Cooler]          
            List of cooler objects to be compared.
        h : int              
            The smoothing parameter used for the 2D mean filter smoothing.
        d_bp_max : int      
            The maximum genomic distance between contacts that will be considered for
            calculating the SCC.
        b_down_sample : bool  
            Determines if the input file with more contacts should be downsized
            to the same number of contacts as the other input files.
            Default = False.
        chr_names : list[str]       
            Chromosomes whose SCC should be calculated.
            Default = None, takes all chromosomes.
        chr_exclude : set[str]    
            Chromosomes that should be ignored for SCC calculation.
            Default = None, excludes no chromosomes.

        Returns:
        df : pd.DataFrame
            A pandas dataframe with all comparisons.
    '''
    # TODO: add average SCC functionality
    # TODO: remove redundant calculations

    # Initialize empty dict
    matrix_dict = {}

    # Loop through all files and calculate sccs
    for clr in clrs:
        file_name = get_cool_name(clr)
        comparisons = bulk_compare_ref(clrs, clr, h, d_bp_max, b_down_sample, chr_names, chr_exclude)
        matrix_dict[file_name] = comparisons
    
    # Convert to dataframe
    df = pd.DataFrame(matrix_dict)

    return df

def sample_scc_dist(x1, x2, bin_size, h=1, d_bp_max=1_000_000, b_down_sample=False, 
                   chr_names = None, chr_exclude = None, chr_lengths = None):
    
    '''
        Takes two lists of .mcool/.cool files and returns a distance matrix for all contact
        map comparisons possible between the arrays. Uses a standard average SCC if no
        chromosome lengths are provided, uses a weighted average if they are.

        Parameters
        ----------
        x1 : list[str]        
            A list of all .mcool/.cool files.
        x2 : list[str]         
            A list of all .mcool/.cool files.
        bin_size : int
            Bin size in both mcool files that will be used to compute the SCC.
            If inputs are .cool files, this parameter is ignored.
        h : int         
            The smoothing parameter used for the 2D mean filter smoothing.
            Default = 1.
        d_bp_max : int 
            The maximum genomic distance between contacts that will be considered for
            calculating the SCC.
            Default = 1_000_000
        b_down_samp : bool
            Determines if the input file with more contacts should be downsized
            to the same number of contacts as the other input file.
            Default = False.
        chr_names : list[str]       
            Chromosomes whose SCC should be calculated.
            Default = None, takes all chromosomes.
        chr_exclude : set[str]    
            Chromosomes that should be ignored for SCC calculation.
            Default = None, excludes no chromosomes.
        chr_lengths : list[int] 
            The lengths of the chromosomes for the included data.
            Default = None, uses a non-weighted average instead.
        
        Returns
        -------
        1 - dist : np.ndarray
            Distance matrix between all included .(m)cool files.

    '''
    # Getting list lengths
    n1 = len(x1)
    n2 = len(x2)
    
    # Define distance matrix
    dist = np.zeros((n1, n2))

    # Looping over all combinations
    for i in range(n1):  # Loop over indices to enable appending to dist matrix
        cmap1 = x1[i]

        for j in range(n2):
            cmap2 = x2[j]

            # Calculate SCCs
            scc = calc_scc_file(cmap1, cmap2, bin_size, h, d_bp_max, b_down_sample, 
                           chr_names, chr_exclude)
            
            # Averages handling
            if chr_lengths == None:
                scc_avg = avg_scc(scc)
            else:
                scc_avg = avg_scc_weighted(scc, chr_lengths)
            
            # Adding to distance matrix
            dist[i, j] = scc_avg

    return 1 - dist # Subtract dist from 1 to get distances between samples instead of similarities